---
#amq_streams_kafka_config_dir: "/etc/{{ amq_streams_kafka_service_name }}/config"
#amq_streams_kafka_log_dir: "/var/log/{{ amq_streams_kafka_service_name }}"
#amq_streams_zookeeper_log_dir: "/var/log/{{ amq_streams_zookeeper_service_name }}"

- name: Set Kafka config dir
  set_fact:
    amq_streams_kafka_config_dir: "{{ amq_streams_home_dir }}/config"
  when: amq_streams_kafka_config_dir is not defined

- name: Set Kafka log config file
  set_fact:
    amq_streams_kafka_config_file: "{{ amq_streams_kafka_config_dir }}/{{ amq_streams_kafka_config_file_name }}"

- name: Set Kafka log dir
  set_fact:
    amq_streams_kafka_log_dir: "{{ amq_streams_home_dir }}/logs"
  when: amq_streams_kafka_log_dir is not defined

- name: Create Kafka working directories
  file:
    path: "{{ item }}"
    owner: "{{ amq_streams_user }}"
    group: "{{ amq_streams_group }}"
    state: directory
  with_items:
    - "{{ amq_streams_kafka_base_dir }}"
    - "{{ amq_streams_kafka_config_dir }}"
    - "{{ amq_streams_kafka_log_dir }}"


- include_tasks: set_zookeeper_facts.yml
  when: amq_streams_kafka_zookeeper_connect is not defined

- name: Set Kafka Zookeeper connect property
  set_fact:
    amq_streams_kafka_zookeeper_connect: "{{ amq_streams_zookeeper_server_list | map(attribute='client_host_port') | list | join(',') }}"
  when: amq_streams_kafka_zookeeper_connect is not defined

- name: Create Kafka Configuration file
  template:
    src: server.properties.j2
    dest: "{{ amq_streams_kafka_config_file }}"
    owner: "{{ amq_streams_user }}"
    group: "{{ amq_streams_group }}"
  notify:
    - Restart kafka
  tags:
    - configure

- name: Set JAVA_HOME environment variable
  set_fact:
    amq_streams_kafka_environ: '{{ amq_streams_kafka_environ | combine({ "JAVA_HOME" : amq_streams_java_home }) }}'
  when: amq_streams_java_home is defined

- name: Set LOG_DIR environment variable
  set_fact:
    amq_streams_kafka_environ: '{{ amq_streams_kafka_environ | combine({ "LOG_DIR" : amq_streams_kafka_log_dir }) }}'
  when: amq_streams_kafka_log_dir is defined

- name: Create Kafka Service file
  template:
    src: kafka.service.j2
    dest: "{{ amq_streams_kafka_service_file }}"
  notify:
    - Systemd reload
    - Restart kafka
  tags:
    - configure